services:
  database:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
      - db_user_password
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.local`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.phpmyadmin-auth.basicauth.users=admin:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/" # admin/password
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-auth"
    networks:
      - app_network
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
    container_name: projet-devops-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.local`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.middlewares.web-rate-limit.rateLimit.average=20"
      - "traefik.http.middlewares.web-rate-limit.rateLimit.burst=10"
      - "traefik.http.routers.web.middlewares=web-rate-limit"
    networks:
      - app_network
    secrets:
      - db_user_password
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  traefik:
    image: traefik:v3.0
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
    networks:
      - app_network

volumes:
  db_data:
  traefik-data:

networks:
  app_network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
