entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080" # Ajout pour exposer l'API sur un port spécifique

api:
  dashboard: true
  insecure: false

ping: {}

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: hicham.smail7@gmail.com
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/traefik.local.crt"
        keyFile: "/certs/traefik.local.key"
  certificates:
    - certFile: "/certs/traefik.local.crt"
      keyFile: "/certs/traefik.local.key"
      stores:
        - default
      domains:
        - main: "web.local"
          sans:
            - "www.web.local"

middlewares:
  default-rate-limit:
    rateLimit:
      average: 20
      burst: 10

log:
  level: DEBUG

accessLog:
  filePath: "/certs/access.log"
