entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: hicham.smail7@gmail.com
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web

middlewares:
  default-rate-limit:
    rateLimit:
      average: 20
      burst: 10

log:
  level: DEBUG

accessLog:
  filePath: "/certs/access.log"
